### ISSUE TITLE
State design pattern for GameClient.inGame

### ISSUE THREAD

**Issue by achooie** [nickhh/senior-design-game#6]
Instead of:
`boolean GameClient.inGame`
use state machine design pattern:

```
if not connected
  up/etc for menu navigation
if connected
  if not in game
    up/etc for menu navigation
  if in game
    up/etc sends a "move up" message
```

**Comment by nicholashh** [comment]
as @achuie pointed out, the view needs to be notified, as well, when we enter a game

**Comment by nicholashh** [comment]
1) we're not doing state design pattern (too OO)
2) perhaps the view should /not/ know...
